name = "GeostatInversion"
authors = ["Daniel O'Malley <omalled@lanl.gov>", "Velimir V Vesselinov <velimir.vesselinov@gmail.com>"]
uuid = "acd30bff-8734-59b1-86d1-c3ef2efb63d6"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
RobustPmap = "27aeedcb-f738-516b-a0b8-3211cf1146e5"
